version:
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=quest_nadir
      - MYSQL_ROOT_PASSWORD=12345

gateway:
  build: ./gateway
  ports:
    - "8080:8080"
  depends_on:
    - server
  environment:
    - SERVER_PORT=8080
    - SHAREIT_SERVER_URL=http://server:9090

server:
  build: ./server
  ports:
    - "9090:9090"
  depends_on:
    - db
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/quest_nadir
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=iamroot